const COMMANDS: &[&str] = &[
    "doc_create", "open_external_file", "take_launch_file", "open_default_apps", "doc_get", "widget_doc_get", "widget_doc_save", "doc_save", "doc_delete", "doc_toggle_pin", "doc_set_goal", "doc_move", "doc_search", "doc_list_by_workspace", "backlinks_get", "implicit_links_get", "usage_record", "tabs_get", "tabs_set", "log_get_or_create", "log_list_entries", "graph_query", "backlinks_extract", "unlinked_mentions", "entities_list", "entity_occurrences", "entities_backfill", "reader_update_position", "reader_set_shelf_status", "reader_set_rating", "reader_get_bookshelf", "reader_import_book", "novel_get_beat_board", "novel_compile", "bible_scope_id", "bible_get_facts", "bible_upsert_fact", "bible_delete_fact", "bible_get_mentions", "bible_upsert_mention", "bible_delete_mentions", "bible_get_suggestions", "bible_confirm_suggestion", "bible_reject_suggestion", "bible_extract_mentions", "bible_rebuild_memory", "conversation_create", "conversation_list", "conversation_add_message", "conversation_get_messages", "ai_generate", "ai_generate_stream", "memory_decay_activity", "memory_smart_tabs", "memory_record_metric", "memory_get_metrics", "craft_metrics_trend", "dashboard_recent_docs", "dashboard_workspace_counts", "dashboard_writing_days", "dashboard_patterns", "dashboard_goals", "get_reopen_never_finish", "dashboard_streak_heatmap", "dashboard_writing_time_patterns", "dashboard_writing_velocity", "dashboard_productivity_score", "script_character_list", "script_character_add", "script_location_list", "script_location_add", "script_timeline_get", "script_timeline_add", "script_role_list", "script_role_assign", "script_role_create", "script_role_delete", "vault_rename_preview", "vault_rename_execute", "atomic_save", "widget_atomic_save", "setup_file_watcher", "memory_get_streak", "doc_search_full", "doc_get_stats", "snapshot_create", "snapshot_list", "snapshot_restore", "snapshot_delete_old", "backup_create", "backup_list", "rag_chunk_document", "rag_search", "rag_get_context", "search_docs_fts", "reindex_fts", "get_doc_tags", "add_doc_tag", "remove_doc_tag", "search_by_tag"
];

fn main() {
    tauri_build::try_build(
        tauri_build::Attributes::new().app_manifest(tauri_build::AppManifest::new().commands(COMMANDS)),
    )
    .unwrap();
}
